version: '3.8'
services:
  app:
    image: clothing-store:0.0.2
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT= 8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db/store_app_db

  postgres-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Azat
    ports:
      - "15432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
